# Generated by Django 5.2.1 on 2025-05-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_products_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
