# Generated by Django 5.2.1 on 2025-06-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_cart_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="session_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
